require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'sushione' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  if !ENV['CI']
    use_flipper!({ 'Flipper' => '0.80.0' })
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

    pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

    post_install do |installer|
      flipper_post_install(installer)
    end
  end
end
